### ISSUE TITLE
How to run stored procedures?

### ISSUE THREAD

**Issue by josefrichter** [rowland/fb#16]
Hi, is there a way to run Firebird's stored procedures using this gem, please? Thank you.

**Comment by BananaPower** [comment]
Hi! I'm trying to use `conn.execute("execute procedure foo('bar');)` and receive this:
`Fb::Error: Unsuccessful execution caused by system error that does not preclude successful execution of subsequent statements
message length error (encountered 0, expected 8)`.
Can you help me, please? Thank you.

**Comment by rowland** [comment]
If that doesn't work, I don't know what will. Sorry.
